---
# GitHub workflow for commits pushed to the Heart repo

name: CI at GitHub
on: [push]

jobs:
  Java8-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --console=plain --no-daemon

  Java8-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --console=plain --no-daemon

  Java8-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --console=plain --no-daemon

  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --console=plain --no-daemon

  Java11-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --console=plain --no-daemon

  Java11-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --console=plain --no-daemon

  Java14-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --console=plain --no-daemon

  Java14-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --console=plain --no-daemon

  Java14-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --console=plain --no-daemon
